In [1]:
import pandas as pd
import numpy as np

In [2]:
datasets=pd.read_csv('IMDB Dataset.csv').sample(1000)
datasets

review sentiment
48006  first real movie in this year. amazing long sh...  positive
43807  It seems a lot of Europeans and Americans see ...  positive
23469  CAUTION: Potential Spoilers Ahead!<br /><br />...  positive
36475  ...they bothered making this movie? Anyone? I ...  negative
22672  What a disappointment, especially in light of ...  negative
...                                                  ...       ...
12782  Following his role in the fine caper SEVEN THI...  negative
48093  Otto Preminger directs this light as a feather...  negative
40270  Parsifal (1982) Starring Michael Kutter, Armin...  positive
29484  It´s long time that I and my wife didn´t see s...  negative
28095  Thank goodness not all Dutch people are that r...  positive

[1000 rows x 2 columns]

### Text Cleaning

In [3]:
# converting sentiment into number
datasets['sentiment'].replace({'positive':1,'negative':0},inplace=True)
datasets.head()

review  sentiment
48006  first real movie in this year. amazing long sh...          1
43807  It seems a lot of Europeans and Americans see ...          1
23469  CAUTION: Potential Spoilers Ahead!<br /><br />...          1
36475  ...they bothered making this movie? Anyone? I ...          0
22672  What a disappointment, especially in light of ...          0

In [4]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 48006 to 28095
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     1000 non-null   object
 1   sentiment  1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 23.4+ KB


In [5]:
# Removing HTML tags from the review
import re
clean=re.compile('<.*?>')
re.sub(clean, '', datasets.iloc[1].review)

"It seems a lot of Europeans and Americans see Indian movies for the wrong reason; I see some people are complaining that this movie did not have any dance sequence! A class apart from their Hindi counterparts, Bengali movies tend to be more realistic. Rituparno Ghosh is one of the best young directors in India, being widely known for his choice of subjects for the movies and the strength of his scripts. 'Chokher bali' is a perfect example. A faithful adaptation of the Nobel laureate Tagore's novel dealing with the pursuit of sexual pleasure of a Bengali widow, the director gives a new dimension to the much acclaimed and controversial work."

In [6]:
# function to clean HTML tags
def remove_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [7]:
datasets['review']=datasets['review'].apply(remove_html)
datasets.head()

review  sentiment
48006  first real movie in this year. amazing long sh...          1
43807  It seems a lot of Europeans and Americans see ...          1
23469  CAUTION: Potential Spoilers Ahead!"Steven Spie...          1
36475  ...they bothered making this movie? Anyone? I ...          0
22672  What a disappointment, especially in light of ...          0

In [8]:
# Converting text into lowercase
def lowercase(text):
    return text.lower()

In [9]:
datasets['review']=datasets['review'].apply(lowercase)
datasets.head()

review  sentiment
48006  first real movie in this year. amazing long sh...          1
43807  it seems a lot of europeans and americans see ...          1
23469  caution: potential spoilers ahead!"steven spie...          1
36475  ...they bothered making this movie? anyone? i ...          0
22672  what a disappointment, especially in light of ...          0

In [10]:
# function to remove special character
def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' ' 
    return x       

In [11]:
# Example of removing special character from text
remove_special('sagffh % ght12@3 jh')

'sagffh   ght12 3 jh'

In [12]:
datasets['review']=datasets['review'].apply(remove_special)
datasets.head()

review  sentiment
48006  first real movie in this year  amazing long sh...          1
43807  it seems a lot of europeans and americans see ...          1
23469  caution  potential spoilers ahead  steven spie...          1
36475     they bothered making this movie  anyone  i ...          0
22672  what a disappointment  especially in light of ...          0

In [14]:
# removing stop words(if,and,etc),nltk(natural language tool kit)
import nltk
from nltk.corpus import stopwords

In [17]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [18]:
# removing these words from the text
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [19]:
# function for removing stop words
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    return y

In [21]:
datasets['review']=datasets['review'].apply(remove_stopwords)
datasets

review  sentiment
48006  [first, real, movie, year, amazing, long, shot...          1
43807  [seems, lot, europeans, americans, see, indian...          1
23469  [caution, potential, spoilers, ahead, steven, ...          1
36475  [bothered, making, movie, anyone, think, looki...          0
22672  [disappointment, especially, light, budget, pr...          0
...                                                  ...        ...
12782  [following, role, fine, caper, seven, thieves,...          0
48093  [otto, preminger, directs, light, feather, sto...          0
40270  [parsifal, 1982, starring, michael, kutter, ar...          1
29484  [long, time, wife, see, boring, thriller, defi...          0
28095  [thank, goodness, dutch, people, ruthless, thi...          1

[1000 rows x 2 columns]

In [22]:
# Removing stemming
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [23]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [33]:
ps.stem('loving')

'love'

In [34]:
datasets['review']=datasets['review'].apply(stem_words)
datasets.head()

review  sentiment
48006  [first, real, movi, year, amaz, long, shot, so...          1
43807  [seem, lot, european, american, see, indian, m...          1
23469  [caution, potenti, spoiler, ahead, steven, spi...          1
36475  [bother, make, movi, anyon, think, look, come,...          0
22672  [disappoint, especi, light, budget, provid, te...          0

In [49]:
# joining comma seperate in one sentence
def join_back(list_input):
    return ' '.join(list_input)

In [51]:
datasets['review']=datasets['review'].apply(join_back)
datasets.head()

review  sentiment
48006  first real movi year amaz long shot sometim fi...          1
43807  seem lot european american see indian movi wro...          1
23469  caution potenti spoiler ahead steven spielberg...          1
36475  bother make movi anyon think look come age mov...          0
22672  disappoint especi light budget provid technic ...          0

In [52]:
# generating columns according to the text to count the frequency
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500)

In [53]:
X=cv.fit_transform(datasets['review']).toarray()

In [55]:
X.shape

(1000, 500)

In [57]:
X.

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 2, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [59]:
y=datasets.iloc[:,-1].values
y.shape

(1000,)

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [62]:
x_train.shape,y_train.shape

((800, 500), (800,))

### Training the data with machine learning algorithm

In [63]:
from sklearn.naive_bayes import BernoulliNB,GaussianNB,MultinomialNB

In [64]:
B=BernoulliNB()
G=GaussianNB()
M=MultinomialNB()

In [66]:
B.fit(x_train,y_train)
G.fit(x_train,y_train)
M.fit(x_train,y_train)

MultinomialNB()

In [67]:
y_pred1=B.predict(x_test)
y_pred2=G.predict(x_test)
y_pred3=M.predict(x_test)

In [68]:
from sklearn.metrics import accuracy_score

In [70]:
print('BernoulliNB',accuracy_score(y_test,y_pred1))
print('GaussianNB',accuracy_score(y_test,y_pred2))
print('MultinomialNB',accuracy_score(y_test,y_pred3))

BernoulliNB 0.77
GaussianNB 0.75
MultinomialNB 0.82


In [75]:
test=datasets['review'].iloc[0:1]
test

48006    first real movi year amaz long shot sometim fi...
Name: review, dtype: object

In [76]:
cv.fit(test)

CountVectorizer(max_features=500)

In [79]:
check=cv.transform(test).toarray()
check

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2,
        1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1,
        2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 6, 1]],
      dtype=int64)

In [81]:
# checking the prediction of first column
X[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [85]:
print(M.predict(X[[0]]))  # 1, sentiment is positive
print(G.predict(X[[0]]))
print(B.predict(X[[0]]))

[1]
[1]
[1]


In [100]:
# columns used for building model
cv.get_feature_names_out()

array(['10', '20', 'abl', 'absolut', 'act', 'action', 'actor', 'actual',
       'ad', 'age', 'almost', 'along', 'alreadi', 'also', 'although',
       'alway', 'amaz', 'american', 'anim', 'annoy', 'anoth', 'anyon',
       'anyth', 'anyway', 'appar', 'appear', 'appreci', 'around', 'art',
       'ask', 'atmospher', 'attempt', 'audienc', 'aw', 'away', 'back',
       'bad', 'base', 'basic', 'beauti', 'becom', 'begin', 'behind',
       'believ', 'best', 'better', 'big', 'bit', 'black', 'book', 'bore',
       'boy', 'break', 'bring', 'brother', 'budget', 'call', 'came',
       'camera', 'car', 'care', 'cartoon', 'case', 'cast', 'caus',
       'certainli', 'chang', 'charact', 'child', 'children', 'cinema',
       'citi', 'classic', 'close', 'come', 'comedi', 'comic', 'comment',
       'compar', 'complet', 'consid', 'continu', 'could', 'countri',
       'coupl', 'cours', 'crap', 'creat', 'cut', 'dark', 'daughter',
       'david', 'day', 'de', 'dead', 'deal', 'death', 'decent', 'decid',
       '